language: java

after_success:
- mvn clean package bundle:bundle
- mvn deploy:deploy-file -Dfile=target/dashboard-1.0-SNAPSHOT.jar -Durl=https://oss.sonatype.org/content/repositories/snapshots -DrepositoryId=ossrh -DpomFile=pom.xml --settings travis-settings.xml -DskipTests=true -B

env:
  global:
  - SONATYPE_USERNAME=crescoedge
  - secure: rgGGnySx4pd6kgbxxVSFnG/PRznbFaxsUuYQ2WGutxzSHg+0jWE6UTcOZTi++RT2x5Ib6DLRIwTamQeCZkAy/xsuYUKS4xIZMQN5zCqYeX2m5c93jzSVomMq+1kcMkcE4bF0rv/hLG8jVKB/2R7Ubfcwyn4MZk5zPgFmD03t4OGKv46o75clwtSJZOjISnJowwrGVZA3u/UaEI5XthwO0WJkp1mMGqzoyuCfgjqhOQ0ebFhtnL7YheZjuMWtWp4LQZgY7FYRTetXInwgl/s0sm6cM/1CZaFE+35CGe8wkvB46k05iQmt6iP5bOqog1AtInNXkECTUHw12t7ZwLdnIfME88VyBLHGHXNzrf3cLiIa6reF3XiBci1+VZMbCqPbm6DRZIxz9DrgA6abnqIm8RcLw03vy1UmkVWkzGW6O2snNpze0I9PsHVwgvi7ShAP6WEc1QNrfeKY4JhGeLevOddBduYQ6diBV1L1JVYn7AN0qQ4g7zXdbKgjf+wvfJA//dzOVcZkDmXv/emf1Q8PoTI2eQAhpfh9s7hkA9c76XH5O2ZbGc2dnV2Q0ptI81VRfHC6lWiGkyu7alGqj4FG8nTiLBwQu61SUQhYVlo/FovP5h7QWTbe9uYTZR8BZ95nCrkKLgnq3sEKmY9TBuk3gEVfosARM3TfabmaIbH875I=
